services:
  mysql:
    image: percona/percona-server:8.0
    container_name: percona-mysql
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:8.2
    container_name: redis
    restart: always
    env_file:
      - .env
    ports:
      - "${REDIS_PORT}:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}", "--appendonly", "yes", "--notify-keyspace-events", "Ex"]
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
    driver: local
  redis_data: